/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CafeId = string;
export interface CafeProfile {
  'id' : CafeId,
  'averageScores' : CoffeeScores,
  'owner' : Principal,
  'name' : string,
  'availableCoffees' : Array<Coffee>,
  'availableFreeCups' : bigint,
  'roastLevel' : string,
  'location' : Location,
}
export interface Coffee {
  'id' : CoffeeId,
  'name' : string,
  'origin' : string,
  'flavorProfile' : string,
  'roastLevel' : string,
}
export type CoffeeId = string;
export interface CoffeeScores {
  'acidity' : number,
  'balance' : number,
  'aroma' : number,
  'cleanCup' : number,
  'sweetness' : number,
  'flavor' : number,
  'body' : number,
  'fragrance' : number,
  'overall' : number,
  'uniformity' : number,
  'aftertaste' : number,
}
export interface CuppingHistory {
  'acidity' : bigint,
  'balance' : bigint,
  'cleanCup' : bigint,
  'sweetness' : bigint,
  'flavor' : bigint,
  'body' : bigint,
  'fragrance' : bigint,
  'overall' : bigint,
  'uniformity' : bigint,
  'aftertaste' : bigint,
}
export type CuppingId = string;
export interface CuppingSubmission {
  'id' : CuppingId,
  'cafe' : CafeId,
  'scores' : CoffeeScores,
  'user' : Principal,
  'timestamp' : Timestamp,
  'qrCodeId' : QRCodeId,
  'coffeeId' : CoffeeId,
  'intensityLevels' : IntensityLevels,
}
export interface DailyStats {
  'qrCodesRedeemed' : bigint,
  'newUsers' : bigint,
  'cuppingSubmissions' : bigint,
  'cafesRegistered' : bigint,
}
export interface IntensityLevels {
  'acidity' : bigint,
  'balance' : bigint,
  'flavor' : bigint,
  'body' : bigint,
  'fragrance' : bigint,
  'aftertaste' : bigint,
}
export type Level = { 'intermediate' : null } |
  { 'novice' : null } |
  { 'advanced' : null } |
  { 'expert' : null };
export interface Location { 'latitude' : number, 'longitude' : number }
export interface QRCodeData {
  'id' : QRCodeId,
  'redemptionTimestamp' : [] | [Timestamp],
  'cafe' : CafeId,
  'redeemed' : boolean,
  'expiryTime' : Timestamp,
  'user' : Principal,
  'coffee' : CoffeeId,
}
export type QRCodeId = string;
export type Timestamp = bigint;
export interface UserProfile {
  'cuppingHistory' : CuppingHistory,
  'accuracyPercentage' : number,
  'completedCuppings' : bigint,
  'name' : string,
  'level' : Level,
  'progress' : bigint,
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCoffeeToCafe' : ActorMethod<[CafeId, Coffee], undefined>,
  'assignCafeOwner' : ActorMethod<[CafeId, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCafeProfile' : ActorMethod<
    [Principal, string, number, number, string, bigint],
    CafeProfile
  >,
  'exportCafeData' : ActorMethod<[CafeId], string>,
  'generateQRCode' : ActorMethod<[CafeId, CoffeeId], QRCodeData>,
  'getCafeForOwner' : ActorMethod<[], [] | [CafeProfile]>,
  'getCafeProfile' : ActorMethod<[CafeId], [] | [CafeProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCuppingsForCafe' : ActorMethod<[CafeId], Array<CuppingSubmission>>,
  'getCuppingsForUser' : ActorMethod<[Principal], Array<CuppingSubmission>>,
  'getDailyStats' : ActorMethod<[], Array<[string, DailyStats]>>,
  'getFilteredCafes' : ActorMethod<[number, string], Array<CafeProfile>>,
  'getQRCode' : ActorMethod<[QRCodeId], [] | [QRCodeData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemQRCode' : ActorMethod<[QRCodeId], undefined>,
  'removeCoffeeFromCafe' : ActorMethod<[CafeId, CoffeeId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCuppingForm' : ActorMethod<
    [QRCodeId, CoffeeScores, IntensityLevels],
    undefined
  >,
  'updateCafeFreeCups' : ActorMethod<[CafeId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];