/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CafeId = IDL.Text;
export const CoffeeId = IDL.Text;
export const Coffee = IDL.Record({
  'id' : CoffeeId,
  'name' : IDL.Text,
  'origin' : IDL.Text,
  'flavorProfile' : IDL.Text,
  'roastLevel' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CoffeeScores = IDL.Record({
  'acidity' : IDL.Float64,
  'balance' : IDL.Float64,
  'aroma' : IDL.Float64,
  'cleanCup' : IDL.Float64,
  'sweetness' : IDL.Float64,
  'flavor' : IDL.Float64,
  'body' : IDL.Float64,
  'fragrance' : IDL.Float64,
  'overall' : IDL.Float64,
  'uniformity' : IDL.Float64,
  'aftertaste' : IDL.Float64,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const CafeProfile = IDL.Record({
  'id' : CafeId,
  'averageScores' : CoffeeScores,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'availableCoffees' : IDL.Vec(Coffee),
  'availableFreeCups' : IDL.Nat,
  'roastLevel' : IDL.Text,
  'location' : Location,
});
export const QRCodeId = IDL.Text;
export const Timestamp = IDL.Int;
export const QRCodeData = IDL.Record({
  'id' : QRCodeId,
  'redemptionTimestamp' : IDL.Opt(Timestamp),
  'cafe' : CafeId,
  'redeemed' : IDL.Bool,
  'expiryTime' : Timestamp,
  'user' : IDL.Principal,
  'coffee' : CoffeeId,
});
export const CuppingHistory = IDL.Record({
  'acidity' : IDL.Nat,
  'balance' : IDL.Nat,
  'cleanCup' : IDL.Nat,
  'sweetness' : IDL.Nat,
  'flavor' : IDL.Nat,
  'body' : IDL.Nat,
  'fragrance' : IDL.Nat,
  'overall' : IDL.Nat,
  'uniformity' : IDL.Nat,
  'aftertaste' : IDL.Nat,
});
export const Level = IDL.Variant({
  'intermediate' : IDL.Null,
  'novice' : IDL.Null,
  'advanced' : IDL.Null,
  'expert' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'cuppingHistory' : CuppingHistory,
  'accuracyPercentage' : IDL.Float64,
  'completedCuppings' : IDL.Nat,
  'name' : IDL.Text,
  'level' : Level,
  'progress' : IDL.Nat,
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const CuppingId = IDL.Text;
export const IntensityLevels = IDL.Record({
  'acidity' : IDL.Nat,
  'balance' : IDL.Nat,
  'flavor' : IDL.Nat,
  'body' : IDL.Nat,
  'fragrance' : IDL.Nat,
  'aftertaste' : IDL.Nat,
});
export const CuppingSubmission = IDL.Record({
  'id' : CuppingId,
  'cafe' : CafeId,
  'scores' : CoffeeScores,
  'user' : IDL.Principal,
  'timestamp' : Timestamp,
  'qrCodeId' : QRCodeId,
  'coffeeId' : CoffeeId,
  'intensityLevels' : IntensityLevels,
});
export const DailyStats = IDL.Record({
  'qrCodesRedeemed' : IDL.Nat,
  'newUsers' : IDL.Nat,
  'cuppingSubmissions' : IDL.Nat,
  'cafesRegistered' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCoffeeToCafe' : IDL.Func([CafeId, Coffee], [], []),
  'assignCafeOwner' : IDL.Func([CafeId, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCafeProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat],
      [CafeProfile],
      [],
    ),
  'exportCafeData' : IDL.Func([CafeId], [IDL.Text], ['query']),
  'generateQRCode' : IDL.Func([CafeId, CoffeeId], [QRCodeData], []),
  'getCafeForOwner' : IDL.Func([], [IDL.Opt(CafeProfile)], ['query']),
  'getCafeProfile' : IDL.Func([CafeId], [IDL.Opt(CafeProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCuppingsForCafe' : IDL.Func(
      [CafeId],
      [IDL.Vec(CuppingSubmission)],
      ['query'],
    ),
  'getCuppingsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CuppingSubmission)],
      ['query'],
    ),
  'getDailyStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, DailyStats))],
      ['query'],
    ),
  'getFilteredCafes' : IDL.Func(
      [IDL.Float64, IDL.Text],
      [IDL.Vec(CafeProfile)],
      ['query'],
    ),
  'getQRCode' : IDL.Func([QRCodeId], [IDL.Opt(QRCodeData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemQRCode' : IDL.Func([QRCodeId], [], []),
  'removeCoffeeFromCafe' : IDL.Func([CafeId, CoffeeId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCuppingForm' : IDL.Func(
      [QRCodeId, CoffeeScores, IntensityLevels],
      [],
      [],
    ),
  'updateCafeFreeCups' : IDL.Func([CafeId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CafeId = IDL.Text;
  const CoffeeId = IDL.Text;
  const Coffee = IDL.Record({
    'id' : CoffeeId,
    'name' : IDL.Text,
    'origin' : IDL.Text,
    'flavorProfile' : IDL.Text,
    'roastLevel' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CoffeeScores = IDL.Record({
    'acidity' : IDL.Float64,
    'balance' : IDL.Float64,
    'aroma' : IDL.Float64,
    'cleanCup' : IDL.Float64,
    'sweetness' : IDL.Float64,
    'flavor' : IDL.Float64,
    'body' : IDL.Float64,
    'fragrance' : IDL.Float64,
    'overall' : IDL.Float64,
    'uniformity' : IDL.Float64,
    'aftertaste' : IDL.Float64,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const CafeProfile = IDL.Record({
    'id' : CafeId,
    'averageScores' : CoffeeScores,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'availableCoffees' : IDL.Vec(Coffee),
    'availableFreeCups' : IDL.Nat,
    'roastLevel' : IDL.Text,
    'location' : Location,
  });
  const QRCodeId = IDL.Text;
  const Timestamp = IDL.Int;
  const QRCodeData = IDL.Record({
    'id' : QRCodeId,
    'redemptionTimestamp' : IDL.Opt(Timestamp),
    'cafe' : CafeId,
    'redeemed' : IDL.Bool,
    'expiryTime' : Timestamp,
    'user' : IDL.Principal,
    'coffee' : CoffeeId,
  });
  const CuppingHistory = IDL.Record({
    'acidity' : IDL.Nat,
    'balance' : IDL.Nat,
    'cleanCup' : IDL.Nat,
    'sweetness' : IDL.Nat,
    'flavor' : IDL.Nat,
    'body' : IDL.Nat,
    'fragrance' : IDL.Nat,
    'overall' : IDL.Nat,
    'uniformity' : IDL.Nat,
    'aftertaste' : IDL.Nat,
  });
  const Level = IDL.Variant({
    'intermediate' : IDL.Null,
    'novice' : IDL.Null,
    'advanced' : IDL.Null,
    'expert' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'cuppingHistory' : CuppingHistory,
    'accuracyPercentage' : IDL.Float64,
    'completedCuppings' : IDL.Nat,
    'name' : IDL.Text,
    'level' : Level,
    'progress' : IDL.Nat,
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const CuppingId = IDL.Text;
  const IntensityLevels = IDL.Record({
    'acidity' : IDL.Nat,
    'balance' : IDL.Nat,
    'flavor' : IDL.Nat,
    'body' : IDL.Nat,
    'fragrance' : IDL.Nat,
    'aftertaste' : IDL.Nat,
  });
  const CuppingSubmission = IDL.Record({
    'id' : CuppingId,
    'cafe' : CafeId,
    'scores' : CoffeeScores,
    'user' : IDL.Principal,
    'timestamp' : Timestamp,
    'qrCodeId' : QRCodeId,
    'coffeeId' : CoffeeId,
    'intensityLevels' : IntensityLevels,
  });
  const DailyStats = IDL.Record({
    'qrCodesRedeemed' : IDL.Nat,
    'newUsers' : IDL.Nat,
    'cuppingSubmissions' : IDL.Nat,
    'cafesRegistered' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCoffeeToCafe' : IDL.Func([CafeId, Coffee], [], []),
    'assignCafeOwner' : IDL.Func([CafeId, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCafeProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text, IDL.Nat],
        [CafeProfile],
        [],
      ),
    'exportCafeData' : IDL.Func([CafeId], [IDL.Text], ['query']),
    'generateQRCode' : IDL.Func([CafeId, CoffeeId], [QRCodeData], []),
    'getCafeForOwner' : IDL.Func([], [IDL.Opt(CafeProfile)], ['query']),
    'getCafeProfile' : IDL.Func([CafeId], [IDL.Opt(CafeProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCuppingsForCafe' : IDL.Func(
        [CafeId],
        [IDL.Vec(CuppingSubmission)],
        ['query'],
      ),
    'getCuppingsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CuppingSubmission)],
        ['query'],
      ),
    'getDailyStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, DailyStats))],
        ['query'],
      ),
    'getFilteredCafes' : IDL.Func(
        [IDL.Float64, IDL.Text],
        [IDL.Vec(CafeProfile)],
        ['query'],
      ),
    'getQRCode' : IDL.Func([QRCodeId], [IDL.Opt(QRCodeData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemQRCode' : IDL.Func([QRCodeId], [], []),
    'removeCoffeeFromCafe' : IDL.Func([CafeId, CoffeeId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCuppingForm' : IDL.Func(
        [QRCodeId, CoffeeScores, IntensityLevels],
        [],
        [],
      ),
    'updateCafeFreeCups' : IDL.Func([CafeId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };