/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: number;
    longitude: number;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Timestamp = bigint;
export interface CoffeeScores {
    acidity: number;
    balance: number;
    cleanCup: number;
    sweetness: number;
    flavor: number;
    body: number;
    fragrance: number;
    overall: number;
    uniformity: number;
    aftertaste: number;
}
export interface DailyStats {
    qrCodesRedeemed: bigint;
    newUsers: bigint;
    cuppingSubmissions: bigint;
    cafesRegistered: bigint;
}
export interface Coffee {
    id: CoffeeId;
    name: string;
    origin: string;
    flavorProfile: string;
    roastLevel: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface QRCodeData {
    id: QRCodeId;
    redemptionTimestamp?: Timestamp;
    cafe: CafeId;
    redeemed: boolean;
    user: Principal;
    timestamp: Timestamp;
    coffee: CoffeeId;
}
export interface CafeProfile {
    id: CafeId;
    averageScores: CoffeeScores;
    owner: Principal;
    name: string;
    availableCoffees: Array<Coffee>;
    availableFreeCups: bigint;
    roastLevel: string;
    location: Location;
    photos: Array<ExternalBlob>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type CuppingId = string;
export interface CuppingHistory {
    acidity: bigint;
    balance: bigint;
    cleanCup: bigint;
    sweetness: bigint;
    flavor: bigint;
    body: bigint;
    fragrance: bigint;
    overall: bigint;
    uniformity: bigint;
    aftertaste: bigint;
}
export type CoffeeId = string;
export type CafeId = string;
export type QRCodeId = string;
export interface CuppingSubmission {
    id: CuppingId;
    cafe: CafeId;
    scores: CoffeeScores;
    user: Principal;
    timestamp: Timestamp;
    qrCodeId: QRCodeId;
    photo?: ExternalBlob;
    coffee: CoffeeId;
    intensityLevels: IntensityLevels;
}
export interface IntensityLevels {
    acidity: bigint;
    balance: bigint;
    flavor: bigint;
    body: bigint;
    fragrance: bigint;
    aftertaste: bigint;
}
export interface UserProfile {
    cuppingHistory: CuppingHistory;
    accuracyPercentage: number;
    completedCuppings: bigint;
    name: string;
    level: Level;
    progress: bigint;
}
export enum Level {
    intermediate = "intermediate",
    novice = "novice",
    advanced = "advanced",
    expert = "expert"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _dummyUpdateLocation(location: Location): Promise<void>;
    addCoffeeToCafe(cafeId: CafeId, coffee: Coffee): Promise<void>;
    assignCafeOwner(cafeId: CafeId, owner: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCafeProfile(owner: Principal, name: string, latitude: number, longitude: number, roastLevel: string, availableFreeCups: bigint): Promise<CafeProfile>;
    exportCafeData(cafeId: CafeId): Promise<string>;
    generateQRCode(cafeId: CafeId, coffeeId: CoffeeId): Promise<QRCodeData>;
    getCafeForOwner(): Promise<CafeProfile | null>;
    getCafeProfile(cafeId: CafeId): Promise<CafeProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCuppingsForCafe(cafeId: CafeId): Promise<Array<CuppingSubmission>>;
    getCuppingsForUser(user: Principal): Promise<Array<CuppingSubmission>>;
    getDailyStats(): Promise<Array<[string, DailyStats]>>;
    getFilteredCafes(maxDistance: number, minRoastLevel: string): Promise<Array<CafeProfile>>;
    getProfile(user: Principal): Promise<UserProfile | null>;
    getQRCode(qrCodeId: QRCodeId): Promise<QRCodeData | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    redeemQRCode(qrCodeId: QRCodeId): Promise<void>;
    removeCoffeeFromCafe(cafeId: CafeId, coffeeId: CoffeeId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitCuppingForm(qrCodeId: QRCodeId, scores: CoffeeScores, intensityLevels: IntensityLevels, photo: ExternalBlob | null): Promise<void>;
    updateCafeFreeCups(cafeId: CafeId, availableFreeCups: bigint): Promise<void>;
}
import type { CafeId as _CafeId, CafeProfile as _CafeProfile, Coffee as _Coffee, CoffeeId as _CoffeeId, CoffeeScores as _CoffeeScores, CuppingHistory as _CuppingHistory, CuppingId as _CuppingId, CuppingSubmission as _CuppingSubmission, ExternalBlob as _ExternalBlob, IntensityLevels as _IntensityLevels, Level as _Level, Location as _Location, QRCodeData as _QRCodeData, QRCodeId as _QRCodeId, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _dummyUpdateLocation(arg0: Location): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._dummyUpdateLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._dummyUpdateLocation(arg0);
            return result;
        }
    }
    async addCoffeeToCafe(arg0: CafeId, arg1: Coffee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoffeeToCafe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoffeeToCafe(arg0, arg1);
            return result;
        }
    }
    async assignCafeOwner(arg0: CafeId, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCafeOwner(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCafeOwner(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCafeProfile(arg0: Principal, arg1: string, arg2: number, arg3: number, arg4: string, arg5: bigint): Promise<CafeProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createCafeProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_CafeProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCafeProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_CafeProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportCafeData(arg0: CafeId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportCafeData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportCafeData(arg0);
            return result;
        }
    }
    async generateQRCode(arg0: CafeId, arg1: CoffeeId): Promise<QRCodeData> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQRCode(arg0, arg1);
                return from_candid_QRCodeData_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQRCode(arg0, arg1);
            return from_candid_QRCodeData_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCafeForOwner(): Promise<CafeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCafeForOwner();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCafeForOwner();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCafeProfile(arg0: CafeId): Promise<CafeProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCafeProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCafeProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCuppingsForCafe(arg0: CafeId): Promise<Array<CuppingSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCuppingsForCafe(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCuppingsForCafe(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCuppingsForUser(arg0: Principal): Promise<Array<CuppingSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCuppingsForUser(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCuppingsForUser(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyStats(): Promise<Array<[string, DailyStats]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyStats();
            return result;
        }
    }
    async getFilteredCafes(arg0: number, arg1: string): Promise<Array<CafeProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredCafes(arg0, arg1);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredCafes(arg0, arg1);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQRCode(arg0: QRCodeId): Promise<QRCodeData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQRCode(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQRCode(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async redeemQRCode(arg0: QRCodeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemQRCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemQRCode(arg0);
            return result;
        }
    }
    async removeCoffeeFromCafe(arg0: CafeId, arg1: CoffeeId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCoffeeFromCafe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCoffeeFromCafe(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitCuppingForm(arg0: QRCodeId, arg1: CoffeeScores, arg2: IntensityLevels, arg3: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCuppingForm(arg0, arg1, arg2, await to_candid_opt_n35(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCuppingForm(arg0, arg1, arg2, await to_candid_opt_n35(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateCafeFreeCups(arg0: CafeId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCafeFreeCups(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCafeFreeCups(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_CafeProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CafeProfile): Promise<CafeProfile> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_CuppingSubmission_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CuppingSubmission): Promise<CuppingSubmission> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Level_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Level): Level {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_QRCodeData_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QRCodeData): QRCodeData {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CafeProfile]): Promise<CafeProfile | null> {
    return value.length === 0 ? null : await from_candid_CafeProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QRCodeData]): QRCodeData | null {
    return value.length === 0 ? null : from_candid_QRCodeData_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CafeId;
    averageScores: _CoffeeScores;
    owner: Principal;
    name: string;
    availableCoffees: Array<_Coffee>;
    availableFreeCups: bigint;
    roastLevel: string;
    location: _Location;
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: CafeId;
    averageScores: CoffeeScores;
    owner: Principal;
    name: string;
    availableCoffees: Array<Coffee>;
    availableFreeCups: bigint;
    roastLevel: string;
    location: Location;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        averageScores: value.averageScores,
        owner: value.owner,
        name: value.name,
        availableCoffees: value.availableCoffees,
        availableFreeCups: value.availableFreeCups,
        roastLevel: value.roastLevel,
        location: value.location,
        photos: await from_candid_vec_n12(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QRCodeId;
    redemptionTimestamp: [] | [_Timestamp];
    cafe: _CafeId;
    redeemed: boolean;
    user: Principal;
    timestamp: _Timestamp;
    coffee: _CoffeeId;
}): {
    id: QRCodeId;
    redemptionTimestamp?: Timestamp;
    cafe: CafeId;
    redeemed: boolean;
    user: Principal;
    timestamp: Timestamp;
    coffee: CoffeeId;
} {
    return {
        id: value.id,
        redemptionTimestamp: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.redemptionTimestamp)),
        cafe: value.cafe,
        redeemed: value.redeemed,
        user: value.user,
        timestamp: value.timestamp,
        coffee: value.coffee
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cuppingHistory: _CuppingHistory;
    accuracyPercentage: number;
    completedCuppings: bigint;
    name: string;
    level: _Level;
    progress: bigint;
}): {
    cuppingHistory: CuppingHistory;
    accuracyPercentage: number;
    completedCuppings: bigint;
    name: string;
    level: Level;
    progress: bigint;
} {
    return {
        cuppingHistory: value.cuppingHistory,
        accuracyPercentage: value.accuracyPercentage,
        completedCuppings: value.completedCuppings,
        name: value.name,
        level: from_candid_Level_n21(_uploadFile, _downloadFile, value.level),
        progress: value.progress
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CuppingId;
    cafe: _CafeId;
    scores: _CoffeeScores;
    user: Principal;
    timestamp: _Timestamp;
    qrCodeId: _QRCodeId;
    photo: [] | [_ExternalBlob];
    coffee: _CoffeeId;
    intensityLevels: _IntensityLevels;
}): Promise<{
    id: CuppingId;
    cafe: CafeId;
    scores: CoffeeScores;
    user: Principal;
    timestamp: Timestamp;
    qrCodeId: QRCodeId;
    photo?: ExternalBlob;
    coffee: CoffeeId;
    intensityLevels: IntensityLevels;
}> {
    return {
        id: value.id,
        cafe: value.cafe,
        scores: value.scores,
        user: value.user,
        timestamp: value.timestamp,
        qrCodeId: value.qrCodeId,
        photo: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.photo)),
        coffee: value.coffee,
        intensityLevels: value.intensityLevels
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    novice: null;
} | {
    advanced: null;
} | {
    expert: null;
}): Level {
    return "intermediate" in value ? Level.intermediate : "novice" in value ? Level.novice : "advanced" in value ? Level.advanced : "expert" in value ? Level.expert : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CuppingSubmission>): Promise<Array<CuppingSubmission>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CuppingSubmission_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CafeProfile>): Promise<Array<CafeProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CafeProfile_n10(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Level_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): _Level {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n36(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cuppingHistory: CuppingHistory;
    accuracyPercentage: number;
    completedCuppings: bigint;
    name: string;
    level: Level;
    progress: bigint;
}): {
    cuppingHistory: _CuppingHistory;
    accuracyPercentage: number;
    completedCuppings: bigint;
    name: string;
    level: _Level;
    progress: bigint;
} {
    return {
        cuppingHistory: value.cuppingHistory,
        accuracyPercentage: value.accuracyPercentage,
        completedCuppings: value.completedCuppings,
        name: value.name,
        level: to_candid_Level_n33(_uploadFile, _downloadFile, value.level),
        progress: value.progress
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Level): {
    intermediate: null;
} | {
    novice: null;
} | {
    advanced: null;
} | {
    expert: null;
} {
    return value == Level.intermediate ? {
        intermediate: null
    } : value == Level.novice ? {
        novice: null
    } : value == Level.advanced ? {
        advanced: null
    } : value == Level.expert ? {
        expert: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
